
language: objective-c
osx_image: xcode7.3
xcode_workspace: PushStarter.xcworkspace
xcode_scheme: PushStarter
xcode_sdk: iphonesimulator

before_install:
  - pod repo update

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master